# Generated by Django 3.2.4 on 2021-06-10 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stonk_app', '0002_alter_stocks_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocks',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
