# Generated by Django 3.2.4 on 2021-06-11 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stonk_app', '0003_alter_stocks_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Stocks',
        ),
    ]
